image: node:latest

stages:
 - init
 - build
 - test
 - quality
 - package
  
variables:
 GIT_SUBMODULE_STRATEGY: recursive
 DISPLAY_NAME: "Tour de France UI"

init:node:
 stage: init
 script:
  - npm install
 artifacts:
  expire_in: 10 mins
  paths:
   - node_modules/

build:node:
 stage: build
 script:
  - ./node_modules/.bin/ng build --aot
 dependencies:
  - init:node

#test:node:
# stage: test
# script:
#  - ./node_modules/.bin/ng test --watch false --single-run
# dependencies:
#  - init:node

lint:node:
 stage: quality
 script:
  - ./node_modules/.bin/ng lint
 dependencies:
  - init:node
 allow_failure: true

sonarqube:node:
 stage: quality
 image: ciricihq/gitlab-sonar-scanner
 script:
  # Install nodejs to enable sonarTS
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get install -y nodejs
  - sonar-scanner -Dsonar.projectKey=gitlab:$CI_PROJECT_ID -Dsonar.organization=pierresebastien-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN -Dsonar.sources=./src -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.projectName="$DISPLAY_NAME"
 dependencies:
  - init:node
 only:
  - develop
  - master

package:node:
 stage: package
 script:
  - ./node_modules/.bin/ng build --prod
 dependencies:
  - init:node
 artifacts:
  name: "$CI_PROJECT_NAME_$CI_COMMIT_TAG"
  paths:
   - dist/
 only:
  - tags